### PR TITLE
Added accessibility role to view titles

### PR DESCRIPTION
**Pull request by AbubakarSambo**
This PR addresses issue #7

### CODE REVIEW

**Comment by svinkle** [comment]
@AbubakarSambo Thanks, although this covers one instance of `variant="bodyTitle"`. There are many throughout the app.

Please also provide a brief description of what the PR is for, referencing the related issue ticket.

**Comment by svinkle** [comment]
@AbubakarSambo This is looking good. I'm noticing now there are more `Text` components which should be headers but do not feature the `variant="bodyTitle"` prop.

For example:
- The status `Sheet` sections, "Push notifications are {status}", "COVID Shield code".
- Each section text on the Privacy view.
- Code form view "Please enter your 8 digit code…" text. Basically any text which starts a new section or view.
- Each section title in the onboarding process and "How COVID Shield works" views
- "Share app" and "Language" for their respective views

**Comment by AbubakarSambo** [comment]
> @AbubakarSambo This is looking good. I'm noticing now there are more `Text` components which should be headers but do not feature the `variant="bodyTitle"` prop.
> 
> For example:
> 
> * The status `Sheet` sections, "Push notifications are {status}", "COVID Shield code".
> * Each section text on the Privacy view.
> * Code form view "Please enter your 8 digit code…" text. Basically any text which starts a new section or view.
> * Each section title in the onboarding process and "How COVID Shield works" views
> * "Share app" and "Language" for their respective views

okay, will fix those too

**Comment by AbubakarSambo** [comment]
Hi @svinkle, I've been having some trouble figuring out the right way to add the header role to the privacy policy page, as it is in markdown. Is there a way you would recommend?

**Comment by jordanAtShopify** [comment]
@AbubakarSambo I think we can ignore the Markdown in the privacy policy page and tackle that in a separate task.

**Comment by svinkle** [comment]
@AbubakarSambo This is a huge improvement, thanks.

I think a few more are missing. Is it possible to add this to each view header? Share app, Change language, Privacy policy, etc. Each of these have a title at the very top of the screen next to there "close" or "back" controls.

**Comment by AbubakarSambo** [comment]
Hey @svinkle, Yes absolutely, I'll add them. sorry i missed it

**Comment by AbubakarSambo** [comment]
Hi @svinkle , I realised that because all the titles share the same Toolbar component, It's already been added to "Language", "Privacy Policy", and "Share app". Is that what you meant?

I had 2 questions though, 
for the "close"/"back" controls, do you think we need to add a `accessibilityRole = button` to them ? 
and for the "Check Symptoms" menu item, should we add a `accessibilityRole= link` ?

**Comment by svinkle** [comment]
> It's already been added to "Language", "Privacy Policy", and "Share app".

I'm testing on `master` and am not experiencing this. If you can add it to one single location that'd be great.

> for the "close"/"back" controls, do you think we need to add a `accessibilityRole = button` to them ?

Yes, #4 outlines this requirement.

**Comment by AbubakarSambo** [comment]
> I'm testing on master and am not experiencing this. If you can add it to one single location that'd be great.

Oh, did you run this branch `AbubakarSambo:fix/headeraccesibility `, Its added it on this current PR, so not merged to master yet

> Yes, #4 outlines this requirement.

Okay, I'll tackle that too, thanks

**Comment by svinkle** [comment]
Ah, I see the issue. [`Toolbar.tsx:46`](https://github.com/CovidShield/mobile/blob/3631cbec3a2d6c1088906bcf6a59860bfef4b7bf/src/components/Toolbar.tsx#L46) also needs the change for iOS. Other than this I think we're good to go here.

**Comment by jordanAtShopify** [comment]
@AbubakarSambo Sorry! This looks good, just removed some extra xcode changes that popped in

**Pull request merged**
