### PR TITLE
Disables animation playing if user has ReducedMotion device setting

### PR DESCRIPTION
**Pull request by jordanAtShopify**
Fixes https://github.com/CovidShield/mobile/issues/50

This will just totally disable playing animations if user has ReducedMotion device setting. I think this is fine over playing once or something more complicated.

### CODE REVIEW

**Comment by svinkle** [comment]
@jordanAtShopify I'm seeing the Home screen animation persists for both Android and iOS.

For the "How it works" screens, Android is paused but iOS remains (maybe it's my simulator misbehaving?)

Either way, I feel like the animation should run at least once to provide context. Otherwise it looks like a bunch of meaningless dots on the screen. Thoughts?

**Comment by kpeatt** [comment]
I have the same issues as Scott. Homescreen animations continue to play when reduced motion is active. I also agree that the animation should run once for context or be paused on a more illustrative frame.

**Comment by kpeatt** [comment]
Also seeing sheet transitions with reduce motion on on a real device. Here's a video:

http://screenshot.click/iOS-recording-0528-120183.mov

**Comment by jordanAtShopify** [comment]
@kpeatt @svinkle ok I fixed it up to disable the animations properly if the app is already open, should behave properly now.

My worry with having the animations play once is that on android the setting is called "Remove Animation" - having all the animations play once normally doesn't seem like a big enough change IMO.

If we want them to always play once maybe we should lower the speed of them to half?

**Comment by kpeatt** [comment]
@jordanAtShopify That's a good point. Is it possible to freeze the animation on a specific frame if that setting is turned on?

**Comment by jordanAtShopify** [comment]
@kpeatt I added the freezing on specific frames for the onboarding animation

**Comment by svinkle** [comment]
@jordanAtShopify This is great! Nice work.

**Comment by jordanAtShopify** [comment]
@henrytao-me there is an option under accessibility settings on android called "Remove Animation" for this

**Comment by svinkle** [comment]
@henrytao-me Just trying this on Android; I'm not seeing the specific frames which appear in iOS.

**Comment by jordanAtShopify** [comment]
@svinkle ya investigating this some more, I can't actually get `isReduceMotionEnabled` to be true on Android. Looks like the animation accessibility option on android does it at a hardware level and doesn't actually let us use the flag, which means we can't really show a specific frame.

**Comment by jordanAtShopify** [comment]
@svinkle the problem is still that we don't know when Android has disabled animations so we could replace it with images on iOS but on Android it always appears as if users have animations on from the code.

**Comment by svinkle** [comment]
> the problem is still that we don't know when Android has disabled animations

That's a bit confusing as when I disable animations in my Android emulator I see the still-frame dots. So, it's kind of working? 🤷‍♂️

**Comment by jordanAtShopify** [comment]
Ya that's what I mean by "android does it at a hardware level" it seems to stop all animations by itself, while on iOS it is up to the app to stop the animations if the setting is enabled.

**Comment by svinkle** [comment]
> it seems to stop all animations by itself

Ahh, I see. Ok, let's leave it as-is and see if we get any comments during usability testing.

**Pull request merged**
