### PR TITLE
git ignore translations file and run on commands instead

### PR DESCRIPTION
**Pull request by jordanAtShopify**
This should help avoid conflicts and make sure translations are in sync when developing.

### CODE REVIEW

**Comment by henrytao-me** [comment]
Close in favor of https://github.com/CovidShield/mobile/issues/93#issuecomment-647084398 and https://github.com/CovidShield/mobile/issues/94#issuecomment-647082267

**Comment by jordanAtShopify** [comment]
@henrytao-me wouldn't we still want this in addition to the watch script? I think running the watch script would be beneficial if someone is actively editing the translations (like jest --watch) but for regular development flow we don't want to require the watch script to be running, right?

**Comment by henrytao-me** [comment]
CI is failing. Can you fix it too? @jordanAtShopify https://github.com/CovidShield/mobile/runs/803431283

**Comment by jordanAtShopify** [comment]
@henrytao-me I fixed it on master

**Pull request merged**
