### PR TITLE
Addresses accessibility issues for privacy policy

### LINKED ISSUE #40: [Privacy policy] Links are not focusable
## Issue summary

When using swipe/touch gestures to navigate through the Privacy Policy, content links do not receive focus. Link text is included in the paragraph text with no notice of their existence. This makes accessing content linked from this view impossible for screen reader users and voice dictation users, leading to a frustrating user experience.

Screen Shot 2020-05-25 at 4 57 57 PM

#### JS

```js
// react-native-markdown-display/renderRules.js

link: (node, children, parent, styles, onLinkPress) => (
  <Text
    key={node.key}
    style={styles.link}
    onPress={() => openUrl(node.attributes.href, onLinkPress)}
  >
    {children}
  </Text>
);
```

## Steps to reproduce

1. Load the app into the iOS or Android simulator
2. Expand the Sheet content
3. Activate the "Read privacy policy" control
3. Enable [VoiceOver screen reader](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) on macOS
4. Use the Virtual Cursor to navigate to the view content

### Expected

- Links to be focusable, announce its label, and conveyed as a "link".

### Actual

- Links are not focusable.

## Recommendation

Since this is a third-party lib, making changes in a timely manner may be difficult. Try to find an alternate markdown renderer, or output the content in a `Text` component, using `Button` components with `accessibleRole="link"` props to output focusable links.

## Specifications

- **Component:** CovidShield [Privacy policy]
- **WCAG Principle:** Operable
- **WCAG SC:** 2.1.1 Keyboard
- **Severity:** High
- **Effort:** Unknown

### PR DESCRIPTION
**Pull request by jordanAtShopify**
Adds better accessibility for markdown rendered nodes for Link and Header in the privacy policy. 

Fixes https://github.com/CovidShield/mobile/issues/40

### CODE REVIEW

**Comment by jordanAtShopify** [comment]
@svinkle let me know if this is any better, I tried adding the external link icon but it broke the link functionality - do you think we are good to skip the icon for this?

**Comment by svinkle** [comment]
@jordanAtShopify The code looks good to me but links are not being generated as I'd expect. Neither are the headings. Is this overriding what the markdown component is generating?

**Comment by jordanAtShopify** [comment]
@svinkle this should just be overriding the default rendering behavior of the react-native-markdown-display package. When you say Links / Headers not being generated as expected you mean that you don't see the accessibility additions when using voice over tools?

**Comment by svinkle** [comment]
> you don't see the accessibility additions when using voice over tools

Exactly. The very top header has the correct `accessibilityRole` applied, but others do not. Also, links still appear to be purely underlined text. They should be singled out as interactive elements.

You can test this by going to Xcode → Open Developer Tool → Accessibility Inspector → click the cross-hair icon → hover over the content in question.

<details>
    <summary>Screenshots</summary>

Screen Shot 2020-06-03 at 11 23 56 AM
Screen Shot 2020-06-03 at 11 24 08 AM
</details>

**Review by henrytao-me — COMMENTED** [review]
Is it possible to move privacy to json file instead of using .js file? 

Regarding to accessibility of link using markdown, we might need to either send PR to react native markdown library or switch to html 🤔

**Comment by jordanAtShopify** [comment]
@henrytao-me what difference would having it in json make?

**Comment by henrytao-me** [comment]
> what difference would having it in json make?

One central place for translation?

**Comment by jordanAtShopify** [comment]
Ah, ya the issue with the json file is that it doesn't support multiline strings and markdown depends on that for formatting. Also, we want it to be as easy as possible to just copy/paste the privacy policy in so we want to avoid any manual formatting steps and keep it close as possible to the original markdown format.

**Review by henrytao-me — COMMENTED** [review]
Can we move the .js from assets to `./src/locale/extras`?

**Pull request closed without merging**
